In [4]:
import nltk


In [2]:
tokens = tokenize_nltk(text)

NameError: name 'tokenize_nltk' is not defined

In [3]:

for token in tokens:
    print(token)

NameError: name 'tokens' is not defined

In [4]:
tok = nltk.tokenize.TreebankWordTokenizer()

In [5]:
from nltk.corpus import stopwords
len(stopwords.words())

4850

In [6]:
stopWords = set(stopwords.words('english'))

In [7]:
stopWords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [1]:
from nlpkf.tokenizer import TokenizerNltk, TokenizerSpacy, Tokenizer
from nlpkf.vectorizers import OneHotGensim, create_word_vectorizer, WordToVec
from nlpkf.utils import text_to_sentence_vecs, text_to_nchunk_vecs, text_to_word_vecs, text_to_vector, clean_text

In [2]:
corpus = [
    "The elephant sneezed at the sight of potatoes. ",
    "Bats can see via echolocation. See the bat sight sneeze!",
    "Wondering, she opened the door to the studio.",
]
text = clean_text("".join(corpus))


In [3]:
x = text_to_word_vecs(text)
len(x), len([i[:3] for i in x]), len(text.split())

(31, 31, 31)

In [4]:
import nltk
list(nltk.ngrams([i[:3] for i in x], 2))

[(array([-0.52547556,  1.8666574 ,  0.13036793], dtype=float32),
  array([-0.57379955,  0.50064933,  2.5647202 ], dtype=float32)),
 (array([-0.57379955,  0.50064933,  2.5647202 ], dtype=float32),
  array([-3.8646727, -2.0901725, -2.6483977], dtype=float32)),
 (array([-3.8646727, -2.0901725, -2.6483977], dtype=float32),
  array([ 3.3111951,  0.5545187, -0.6642161], dtype=float32)),
 (array([ 3.3111951,  0.5545187, -0.6642161], dtype=float32),
  array([0.25327787, 0.87766397, 2.5326617 ], dtype=float32)),
 (array([0.25327787, 0.87766397, 2.5326617 ], dtype=float32),
  array([ 0.7013794,  2.420463 , -0.8726411], dtype=float32)),
 (array([ 0.7013794,  2.420463 , -0.8726411], dtype=float32),
  array([ 2.7941532,  2.0729694, -1.4409533], dtype=float32)),
 (array([ 2.7941532,  2.0729694, -1.4409533], dtype=float32),
  array([-0.06581615,  2.4987152 ,  3.5946229 ], dtype=float32)),
 (array([-0.06581615,  2.4987152 ,  3.5946229 ], dtype=float32),
  array([0.38723868, 2.8492007 , 0.63496786], dt

In [5]:
list(nltk.ngrams(text.split(), 2))

[('The', 'elephant'),
 ('elephant', 'sneezed'),
 ('sneezed', 'at'),
 ('at', 'the'),
 ('the', 'sight'),
 ('sight', 'of'),
 ('of', 'potatoes'),
 ('potatoes', '.'),
 ('.', 'Bats'),
 ('Bats', 'can'),
 ('can', 'see'),
 ('see', 'via'),
 ('via', 'echolocation'),
 ('echolocation', '.'),
 ('.', 'See'),
 ('See', 'the'),
 ('the', 'bat'),
 ('bat', 'sight'),
 ('sight', 'sneeze'),
 ('sneeze', '!'),
 ('!', 'Wondering'),
 ('Wondering', ','),
 (',', 'she'),
 ('she', 'opened'),
 ('opened', 'the'),
 ('the', 'door'),
 ('door', 'to'),
 ('to', 'the'),
 ('the', 'studio'),
 ('studio', '.')]

In [6]:
len(x), x[0]

(31, array([-5.25475562e-01,  1.86665738e+00,  1.30367935e-01,  4.99081898e+00,
        -3.38221788e-02,  1.00722432e+00,  9.34666634e-01,  3.70950490e-01,
         1.35799193e+00,  2.89854097e+00,  9.60064352e-01,  1.47703195e+00,
         6.94060326e-01, -2.92380714e+00, -9.49871242e-01, -3.35054064e+00,
         3.01920557e+00,  3.23980808e-01, -5.87301612e-01,  1.42875504e+00,
         4.22025156e+00,  2.83829999e+00, -1.58517635e+00,  1.47718504e-01,
         4.02612734e+00, -1.98015428e+00,  8.86760712e-01,  9.33763206e-01,
        -1.88373482e+00, -2.32407165e+00,  6.99570403e-03,  4.35480499e+00,
         9.29226160e-01, -3.75017017e-01,  3.80339682e-01, -1.51936579e+00,
         5.54521751e+00, -2.50310397e+00, -1.89730871e+00, -4.35285687e-01,
        -2.05240512e+00, -9.75709498e-01,  1.27878642e+00, -1.76949251e+00,
        -9.02045369e-01, -3.08017468e+00,  2.67038822e+00,  3.18578267e+00,
        -1.22527051e+00,  5.41229963e-01,  3.42318177e-01, -1.01836467e+00,
        

In [13]:
tok = Tokenizer(remove_stopwords=False, use_stems=False,
                    to_lowercase=True, use_lemma=True, remove_punctuation=False)


In [7]:
tok_kwargs = dict(remove_stopwords=True, use_stems=False, to_lowercase=True, use_lemma=False, remove_punctuation=False)
wv = create_word_vectorizer(tokenizer_kwargs=tok_kwargs, binary=False)

In [14]:
len(set(text_to_word_vecs(text, **tok_kwargs)))

TypeError: unhashable type: 'numpy.ndarray'

In [8]:
clean_corpus = wv.fit(corpus)

In [12]:
wv.get_feature_names(), wv.vocabulary_

(['!',
  ',',
  '.',
  'bat',
  'bats',
  'door',
  'echolocation',
  'elephant',
  'opened',
  'potatoes',
  'see',
  'sight',
  'sneeze',
  'sneezed',
  'studio',
  'via',
  'wondering'],
 {'elephant': 7,
  'sneezed': 13,
  'sight': 11,
  'potatoes': 9,
  '.': 2,
  'bats': 4,
  'see': 10,
  'via': 15,
  'echolocation': 6,
  'bat': 3,
  'sneeze': 12,
  '!': 0,
  'wondering': 16,
  ',': 1,
  'opened': 8,
  'door': 5,
  'studio': 14})

In [22]:
clean_corpus.toarray()

array([[0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1]], dtype=int64)

In [29]:
[x[0] for x in sorted(wv.vocabulary_.items(), key=lambda x: x[1])]

['!',
 ',',
 '.',
 'bat',
 'bats',
 'door',
 'echolocation',
 'elephant',
 'opened',
 'potatoes',
 'see',
 'sight',
 'sneeze',
 'sneezed',
 'studio',
 'via',
 'wondering']

In [4]:
res = [clean_text(t) for t in corpus]

In [5]:
w2v = WordToVec()

In [ ]:
from sklearn.base import TransformerMixin, BaseEstimator
class WordToVec(BaseEstimator, TransformerMixin):

    def __init__(self, model:str='en_core_web_sm', vectorizer_kwargs=None, tokenizer_kwargs=None):
        
        self.nlp = spacy.load(model)
        self.vectorizer = create_word_vectorizer(tokenizer_kwargs=tokenizer_kwargs, **vectorizer_kwargs)
        self.tokenizer = Tokenizer(**tokenizer_kwargs)
        self.last_transformed = []
        
    @property
    def vocabulary(self):
        return self.vectorizer.vocabulary_


    def fit(self, X, y=None):
        """
        Learn how to transform data based on input data, X.
        """

        return self

    def transform(self, X):
        """
        Transform X into a new dataset, Xprime and return it.
        """

        for sent in X:
            for word in sent:

In [6]:
import numpy as np
np.array(list((w2v.fit_transform(res)))).shape

ValueError: too many values to unpack (expected 2)

In [10]:
np.array(w2v.fit_transform(res).tolist())

AttributeError: 'list' object has no attribute 'tolist'

In [12]:
x = w2v.fit_transform(res)

In [14]:
x[0].shape, x[1].shape

((5, 384), (10, 384))

In [11]:
wv.vocabulary_

AttributeError: 'CountVectorizer' object has no attribute 'vocabulary_'

In [31]:
tok_corp = tok_sp.fit_transform(corpus, return_tokens=True)

NameError: name 'tok_sp' is not defined

In [30]:
tok_corp

NameError: name 'tok_corp' is not defined

In [22]:
gsv = GensimVectorizer()

In [ ]:
Count

In [21]:
list(gsv.fit_transform(tok_corp))

[array([1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.], dtype=float32),
 array([1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0.,
        0., 0.], dtype=float32),
 array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
        1., 1.], dtype=float32)]

In [6]:
res = tok_sp.fit_transform(corpus)

In [17]:
[" ".join([x for x in sent])  for sent in res ]

['The elephant sneezed sight potato .',
 'Bats see via echolocation . See bat sight sneeze !',
 'Wondering , opened door studio .']

In [47]:
tok_sp.use_stems = False
tok_sp.use_lemma = True

In [30]:
import spacy
nlp = spacy.load('en')


In [10]:
nlp(res)

TypeError: Argument 'string' has incorrect type (expected str, got list)

In [48]:
from sklearn.preprocessing import Binarizer
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = 
vectors = vectorizer.fit_transform([" ".join(a) for a in tok_nltk.fit_transform(corpus)])
vectors = vectorizer.fit_transform(corpus)
freq   = CountVectorizer(tokenizer=tok_sp.tokenize_text)
fit_corpus = freq.fit_transform(corpus)

onehot = Binarizer()
sk_corpus = onehot.fit_transform(fit_corpus.toarray())

In [49]:
import pandas as pd
pd.DataFrame(columns=freq.get_feature_names(), data=fit_corpus.toarray())

!  ,  .  bat  door  echolocation  elephant  opened  potato  see  sight  \
0  0  0  1    0     0             0         1       0       1    0      1   
1  1  0  1    2     0             1         0       0       0    2      1   
2  0  1  1    0     1             0         0       1       0    0      0   

   sneeze  sneezed  studio  via  wondering  
0       0        1       0    0          0  
1       1        0       0    1          0  
2       0        0       1    0          1

In [50]:
import pandas as pd
pd.DataFrame(columns=freq.get_feature_names(), data=fit_corpus.toarray())

!  ,  .  bat  door  echolocation  elephant  opened  potato  see  sight  \
0  0  0  1    0     0             0         1       0       1    0      1   
1  1  0  1    2     0             1         0       0       0    2      1   
2  0  1  1    0     1             0         0       1       0    0      0   

   sneeze  sneezed  studio  via  wondering  
0       0        1       0    0          0  
1       1        0       0    1          0  
2       0        0       1    0          1

In [41]:
freq.vocabulary_

{'elephant': 6,
 'sneezed': 12,
 'sight': 10,
 'potato': 8,
 '.': 2,
 'bat': 3,
 'see': 9,
 'via': 14,
 'echolocation': 5,
 'sneeze': 11,
 '!': 0,
 'wondering': 15,
 ',': 1,
 'opened': 7,
 'door': 4,
 'studio': 13}

In [32]:
sk_corpus, fit_corpus.toarray()

(array([[0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0],
        [1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0],
        [0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1]], dtype=int64),
 array([[0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0],
        [1, 0, 1, 2, 0, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 0],
        [0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1]], dtype=int64))

In [34]:
[" ".join(a) for a in tok_nltk.fit_transform(corpus)]

['elephant sneezed sight potatoes .',
 'bats see via echolocation . see bat sight sneeze !',
 'wondering , opened door studio .']

In [36]:
vectors.toarray()

array([[0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1]], dtype=int64)

In [37]:
import gensim

gs_corpus  = tok_nltk.fit_transform(corpus)
id2word = gensim.corpora.Dictionary(gs_corpus)
vectors = [id2word.doc2bow(doc) for doc in gs_corpus]

In [15]:
[sent.vec for sent in doc.sents]

NameError: name 'doc' is not defined

In [39]:
[
    [(token[0], 1) for token in id2word.doc2bow(doc)]
    for doc in gs_corpus
]

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1)],
 [(0, 1), (3, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1)],
 [(0, 1), (12, 1), (13, 1), (14, 1), (15, 1), (16, 1)]]

In [48]:
import spacy
from spacy.vocab import Vocab
from spacy.attrs import ORTH, LIKE_URL, NORM

nlp = spacy.load('en_core_web_sm')
doc = nlp(u"Check out https://spacy.io")
for token in doc:
    print(token.text, token.orth, token.like_url)

attr_ids = [ORTH, LIKE_URL, NORM]
doc_array = doc.to_array(attr_ids)
print(doc_array.shape)
print(len(doc), len(attr_ids))

assert doc[0].orth == doc_array[0, 0]
assert doc[1].orth == doc_array[1, 0]
assert doc[0].like_url == doc_array[0, 1]

assert list(doc_array[:, 1]) == [t.like_url for t in doc]
print(list(doc_array[:, 1]))

Check 8104846059040039827 False
out 1696981056005371314 False
https://spacy.io 17142293684782158888 True
(3, 3)
3 3
[0, 0, 1]


In [50]:
voc = Vocab()

In [56]:
lex = voc["Apple"]

In [59]:
lex.norm_

''

In [9]:
import spacy
import numpy as np
nlp = spacy.load('en_core_web_md')
 
EMBEDDINGS_LEN = len(nlp.vocab['apple'].vector)
print("EMBEDDINGS_LEN=", EMBEDDINGS_LEN)  # 300
 
embeddings_index = np.zeros((len(wv.get_feature_names()) + 1, EMBEDDINGS_LEN))
for word, idx in word2idx.items():
    try:
        embedding = nlp.vocab[word].vector
        embeddings_index[idx] = embedding
    except:
        pass
 

EMBEDDINGS_LEN= 300


NameError: name 'wv' is not defined

In [31]:
vals = [list(nltk.ngrams(doc.split(" "), 14, pad_left=True, pad_right=True, left_pad_symbol='<#>', right_pad_symbol='<$>')) for doc in corpus]
vals[0]

[('<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  'The'),
 ('<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  'The',
  'elephant'),
 ('<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  'The',
  'elephant',
  'sneezed'),
 ('<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  'The',
  'elephant',
  'sneezed',
  'at'),
 ('<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  'The',
  'elephant',
  'sneezed',
  'at',
  'the'),
 ('<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  'The',
  'elephant',
  'sneezed',
  'at',
  'the',
  'sight'),
 ('<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  'The',
  'elephant',
  'sneezed',
  'at',
  'the',
  'sight',
  'of'),
 ('<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  '<#>',
  'The',

In [25]:
nltk.ngrams?

In [13]:
import torch.nn as nn 

# vocab_size is the number of words in your train, val and test set
# vector_size is the dimension of the word vectors you are using
embed = nn.Embedding(vocab_size, vector_size)

# intialize the word vectors, pretrained_weights is a 
# numpy array of size (vocab_size, vector_size) and 
# pretrained_weights[i] retrieves the word vector of
# i-th word in the vocabulary
embed.weight.data.copy_(torch.fromnumpy(pretrained_weights))

# Then turn the word index into actual word vector
vocab = {"some": 0, "words": 1}
word_indexes = [vocab[w] for w in ["some", "words"]] 
word_vectors = embed(word_indexes)

NameError: name 'vocab_size' is not defined