In [1]:
from nlpkf.vectorizers import WordToVec
from nlpkf.tokenizer import clean_text

In [2]:
corpus = [
    "The elephant sneezed at the sight of potatoes. ",
    "Bats can see via echolocation. See the bat sight sneeze!",
    "Wondering, she opened the door to the studio.", " MOUNTAINS permitors."
]
text = "".join(corpus)

In [13]:
tok_kwargs = dict(remove_stopwords=True, use_stems=False, 
                  to_lowercase=True, use_lemma=True, remove_punctuation=False)

In [14]:
import time
start = time.time()
w2v = WordToVec(tokenizer_kwargs=tok_kwargs, vectorizer_kwargs={})
end = time.time()
print(end - start)

9.785982847213745


In [ ]:
import time
start = time.time()
w2v = WordToVec(tokenizer_kwargs=tok_kwargs, vectorizer_kwargs={})
end = time.time()
print(end - start)

In [5]:
w2v.tokenizer.remove_punctuation = True

In [6]:
w2v.fit(w2v.clean_text(corpus, return_tokens=False) + ["My penis is ridiculous"])

In [10]:
w2v.to_pytorch_embedding(vector_size=64, pretrained=True)

Embedding(17, 300)

In [7]:
w2v.vectorizer.binary = True

In [8]:
w2v.vectorizer.transform(corpus).toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
len(w2v.to_seq_vectors(corpus))

4

NameError: name 'np' is not defined

In [45]:
import torch.nn as nn
import torch
import numpy as np

# vocab_size is the number of words in your train, val and test set
# vector_size is the dimension of the word vectors you are using
vector_size = len(w2v.idx2vec[0])
pretrained_weights = np.array([w2v.idx2vec[i] for i in range(w2v.vocab_size)])

embed = nn.Embedding(w2v.vocab_size, vector_size)

# intialize the word vectors, pretrained_weights is a 
# numpy array of size (vocab_size, vector_size) and 
# pretrained_weights[i] retrieves the word vector of
# i-th word in the vocabulary
embed.weight.data.copy_(torch.from_numpy(pretrained_weights))

# Then turn the word index into actual word vector

word_indexes = torch.LongTensor([w for w in w2v.vocabulary.values()])
word_vectors = embed(torch.arange(w2v.vocab_size)).detach()

In [47]:
all(word_vectors[12].numpy() == w2v.idx2vec[12])

True

In [42]:
word_indexes

tensor([ 6, 16, 14, 11,  2,  3, 13, 18,  5, 15,  0, 19,  1,  8,  4, 17,  7, 10,
         9, 12])

In [43]:
word_vectors[12].numpy()[:10], w2v.idx2vec[12]

(array([-0.082752 ,  0.67204  , -0.14987  , -0.064983 ,  0.056491 ,
         0.40228  ,  0.0027747, -0.3311   , -0.30691  ,  2.0817   ],
       dtype=float32),
 array([-9.1445e-01, -1.8174e-01,  1.9368e-01,  1.3445e-01, -2.4596e-01,
         2.5349e-01,  3.2706e-01, -1.0537e-01,  1.5046e-01,  2.1878e+00,
         9.2471e-02,  9.3998e-02, -1.5824e-02,  5.5601e-01, -1.7520e-01,
        -1.4956e-01, -1.9143e-01, -2.9982e-02,  3.9034e-01, -2.9230e-01,
         1.2081e-03,  1.6841e-01,  2.9684e-01, -3.1493e-01, -1.3577e-01,
        -2.3571e-02, -9.7125e-02, -4.5132e-01,  9.2707e-02, -1.3079e-01,
        -1.3258e-01,  3.9406e-01, -1.9954e-01,  3.1603e-01,  2.4090e-01,
        -1.5074e-02, -5.1176e-02,  2.1314e-01, -6.2006e-02,  4.2745e-01,
        -6.9720e-02,  1.9396e-02, -2.6187e-01,  5.0427e-01,  3.6148e-01,
        -2.1733e-01,  6.8295e-02,  5.5245e-01,  4.3527e-02, -6.7328e-02,
        -1.6001e-03,  2.4306e-01, -1.5300e-01, -5.9906e-02, -2.6155e-01,
        -1.3411e-01,  2.7679e-01, -7.